# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'public/assets/**/*'
    - 'demo_app/**/*'
    - 'examples/**/*'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedStyle: with_fixed_indentation

# Lint
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/RedundantCopDisableDirective:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 3

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/ClassVars:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/ParallelAssignment:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantCondition:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSort:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: percent_r
  MaxSlashes: 0

Style/RescueStandardError:
  Enabled: true

Style/SafeNavigation:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/SignalException:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StringHashKeys:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/RedundantPercentQ:
  Enabled: true

Style/RedundantInterpolation:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/YodaCondition:
  Enabled: true

# Metrics
Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 200

Metrics/ParameterLists:
  Max: 5

Metrics/PerceivedComplexity:
  Max: 10

# Performance
Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConcurrentMonotonicTime:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/DoubleStartEndWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/FixedSize:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/MapMethodChain:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true

Performance/RedundantMatch:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SelectMap:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/StringReplacement:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/TimesMap:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/UriDefaultParser:
  Enabled: true

# Rails
Rails/ApplicationController:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationMailer:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/ContentTag:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/DelegateAllowBlank:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true

Rails/EnumHash:
  Enabled: true

Rails/EnumUniqueness:
  Enabled: true

Rails/Exit:
  Enabled: true

Rails/FilePath:
  Enabled: true

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/LexicallyScopedActionFilter:
  Enabled: true

Rails/LinkToBlank:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/MigrationClassName:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/NotNullColumn:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/OutputSafety:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/Presence:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/RedundantAllowNil:
  Enabled: true

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RedundantReceiverInWithOptions:
  Enabled: true

Rails/ReflectionClassName:
  Enabled: true

Rails/RefuteMethods:
  Enabled: true

Rails/RelativeDateConstant:
  Enabled: true

Rails/RequestReferer:
  Enabled: true

Rails/RequireDependency:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/SafeNavigationWithBlank:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/ScopeArgs:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

Rails/UniqueValidationWithoutIndex:
  Enabled: true

Rails/UnknownEnv:
  Enabled: true

Rails/Validation:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true
