[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect old domain to new domain
[[redirects]]
  from = "https://graphql-ui-layout.com/*"
  to = "https://gem.zeropoint.bg/:splat"
  status = 301

[[redirects]]
  from = "https://www.graphql-ui-layout.com/*"
  to = "https://gem.zeropoint.bg/:splat"
  status = 301

# Redirect www to non-www
[[redirects]]
  from = "https://www.gem.zeropoint.bg/*"
  to = "https://gem.zeropoint.bg/:splat"
  status = 301

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://gem.zeropoint.bg/*"
  to = "https://gem.zeropoint.bg/:splat"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com https://api.github.com; frame-src https://www.youtube.com;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=86400" 