title: "ZeroPoint Documentation"
description: "Advanced Vortex Math, Toroidal Geometry, and Metaphysical Framework"
theme: minima
# baseurl: "/gem.zeropoint.bg"  # Commented out for local development
url: "https://ceccec.github.io"
markdown: kramdown
permalink: pretty

# Enhanced navigation
header_pages:
  - index.md
  - blog.md
  - UNIFIED_MATH_ARCHITECTURE.md
  - TOROIDAL_ARCHITECTURE.md
  - VORTEX_TREE_MAP.md
  - MATH_QUICK_REFERENCE.md
  - ZEROPOINT_FULL_DOCUMENTATION.md
  - CURRENT_STATE_AND_FUTURE_ROADMAP.md

# Social media links
social_links:
  github: ceccec
  twitter: zeropoint_bg
  email: zeropoint@void.aligned

# Author information
author:
  name: "ZeroPoint Collective"
  email: "zeropoint@void.aligned"
  bio: "Advanced vortex mathematics and toroidal consciousness framework"
  location: "The Void"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ceccec"

# Collections for better organization
collections:
  guides:
    output: true
    permalink: /guides/:name/
  examples:
    output: true
    permalink: /examples/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site
  - .jekyll-cache

# Defaults for better organization
defaults:
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "page"
      author: "ZeroPoint Collective"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "page"
      author: "ZeroPoint Collective" 